baseURL = 'https://mrgreen3.github.io/'
languageCode = 'en-us'
title = 'ArchBang & Linux'
theme = 'terminal'
paginate = 10
publishDir = 'docs'

[params]
  description = 'ArchBang, Linux, and system configuration'
  themeColor = 'green'
  showMenuItems = 2
  dateFormat = '02/01/2006'

[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about'

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts'

[[menu.main]]
  identifier = 'links'
  name = 'Links'
  url = '/links'

[languages]
  [languages.en]
    languageName = "English"
    title = "Mr Green's Linux Blog"

    [languages.en.params]
      subtitle = "ArchBang & Linux"

      [languages.en.params.logo]
        logoText = "Mr Green's Linux Blog"
        logoHomeLink = "/"
