baseURL = 'https://mrgreen.blog/'
languageCode = 'en-us'
title = 'ArchBang & Linux'
theme = 'hugo-dead-simple'
paginate = 10
publishDir = 'docs'

[params]
  description = 'ArchBang, Linux, and system configuration'
  showMenuItems = 4

  [params.theme]
    palette = 'custom-green'
  dateFormat = '02/01/2006'
  centerTheme = false
  ReadMore = 'Read more'
  MenuMore = 'Show more'
  ReadOtherPosts = 'Read other posts'
  footer = "© 2026 Mr Green. All rights reserved."

[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about'

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts'

[[menu.main]]
  identifier = 'links'
  name = 'Links'
  url = '/links'

[[menu.main]]
  identifier = 'archive'
  name = 'Archive'
  url = '/archive'

[languages]
  [languages.en]
    languageName = "English"
    title = "Mr Green's Linux Blog"
    subtitle = "ArchBang & Linux"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params]
      subtitle = "ArchBang & Linux"

      [languages.en.params.logo]
        logoText = "Mr Green's Linux Blog"
        logoHomeLink = "/"
