base_url = "https://mrgreen.blog"
title = "Mr Green's Linux Blog"
description = "ArchBang & Linux"

output_dir = "docs"

compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

theme = "terminimal"

taxonomies = [
    { name = "tags" },
]

[markdown]
[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
accent_color = "green"
background_color = "dark"

logo_text = "Mr Green's Linux Blog"
author = "Mr Green"
copyright_html = "© 2026 Mr Green. All rights reserved."

menu_items = [
    { name = "blog", url = "$BASE_URL" },
    { name = "tags", url = "$BASE_URL/tags" },
    { name = "about", url = "$BASE_URL/about" },
    { name = "links", url = "$BASE_URL/links" },
]
