name: Deploy to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          wget -q https://github.com/getzola/zola/releases/download/v0.22.1/zola-v0.22.1-x86_64-unknown-linux-gnu.tar.gz
          tar xzf zola-v0.22.1-x86_64-unknown-linux-gnu.tar.gz
          ./zola build

      - name: Deploy
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "ci@codeberg.org"
          git config --global user.name "Forgejo Actions"
          mkdir /tmp/deploy
          cp -r public/. /tmp/deploy/
          cd /tmp/deploy
          git init
          git remote add origin https://x-token:$TOKEN@codeberg.org/${{ github.repository }}.git
          git add --all
          git commit -m "deploy ${GITHUB_SHA::8} [ci skip]"
          git push origin HEAD:pages --force
